version: "3.1"
services:
    
    kafka:
        image: docker pull wurstmeister/kafka
        restart: always
        environment:
            KAFKA_ZOOKEEPER_CONNECT: ""
            KAFKA_MESSAGE_MAX_BYTES: 2000000
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG
            KAFKA_BROKER_ID: my_broker
            KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
        network_mode: "host"
        depends_on: 
            - kopeeker
    
    kopeeker:
        image: zookeeper
        restart: always
        hostname: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888
